### ISSUE TITLE
Error code when running log4shell.nse

### ISSUE THREAD

**Issue by jaintechAI** [righel/log4shell_nse#3]
NSE: Starting log4shell-righel against A.B.C.D:80.

NSE: log4shell-righel against A.B.C.D:80 threw an error!

attempt to index a nil value

stack traceback:

	[C]: in for iterator 'for iterator'

	C:\Program Files (x86)\Nmap/scripts\log4shell-righel.nse:91: in function <C:\Program Files (x86)\Nmap/scripts\log4shell-righel.nse:56>

	(...tail calls...)

NSE: Starting log4shell-righel against A.B.C.D:443.

NSE: log4shell-righel against A.B.C.D:443 threw an error!

attempt to index a nil value

stack traceback:

	[C]: in for iterator 'for iterator'

	C:\Program Files (x86)\Nmap/scripts\log4shell-righel.nse:91: in function <C:\Program Files (x86)\Nmap/scripts\log4shell-righel.nse:56>

	(...tail calls...)

Completed NSE at 16:52, 0.00s elapsed

Nmap scan report for james.bond.mi5.org (A.B.C.D)

Is there anything I am doing incorrectly?

Thanks

**Comment by righel** [comment]
Hello @jaintechAI 
The error you are getting is in this line:
https://github.com/righel/log4shell_nse/blob/61546c874f4a05462048e7b76da5990e43d9ed64/log4shell.nse#L91

Seems you are missing [templates.json](https://github.com/righel/log4shell_nse/blob/main/templates.json) file in the directory you are running the script, did you renamed it?
If you want to use a custom templates file use the `--script-args id=<uuid>,mode=<mod>,templates=custom_file.json`

Which command line arguments are you using for Nmap?
This works for me:
```
$ nmap --script log4shell.nse --script-args id=3e8f5de0-xxxx-xxxx-xxxx-165bac40a9f5,mode=huntress A.B.C.D
Starting Nmap 7.80 ( https://nmap.org ) at 2022-01-13 18:15 CET
Nmap scan report for A.B.C.D (X.X.X.X)
Host is up (0.025s latency).
Not shown: 998 filtered ports
PORT    STATE SERVICE
80/tcp  open  http
|_log4shell: Check https://log4shell.huntress.com/view/3e8f5de0-xxxx-xxxx-xxxx-165bac40a9f5 for results.
443/tcp open  https
|_log4shell: Check https://log4shell.huntress.com/view/3e8f5de0-xxxx-xxxx-xxxx-165bac40a9f5 for results.

Nmap done: 1 IP address (1 host up) scanned in 8.80 seconds
``` 

Let me know if that helps.

**Comment by jaintechAI** [comment]
Luciano,

Yes, the file was there but had a typo error. All good now.

Many thanks for your good work.
